@echo off
rem Copyright 2017 The Chromium Authors. All rights reserved.
rem Use of this source code is governed by a BSD-style license that can be
rem found in the LICENSE file.

setlocal
set PYTHON_BAT_RUNNER=1

::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::
::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::::

rem This file is automatically generated by "bootstrap\win\win_tools.py", and
rem should not be modified.
::
rem The previous "::" block acts as a nop-sled. Each time a batch file executes
rem a command, it reloads itself and seeks to its previous execution offset to
rem begin execution. Updating this batch file is, therefore, risky, since any
rem running Python instance that is using the old batch file will reload the new
rem batch file once the Python command terminates and resume at some unknown
rem offset.
::
rem With the sled in place, a previous instance will resume mid-label. We are
rem assuming that the offset of the Python invocation is greater than the
rem PYTHON_BAT_RUNNER set command, which is the case since the old instance has
rem a large PATH set block before the Python execution. Old instances will hit
rem the next block of code without PYTHON_BAT_RUNNER set. New instances will have
rem it set.
::
rem We remedy this in the future by having the batch file load its core paths
rem from an external file with for/set, removing the need to modify "python.bat"
rem during upgrade.
::
rem After all of the old batch files are believed to be replaced, we can remove
rem the PYTHON_BAT_RUNNER block and the sled. For this update, old instances
rem will resume past the end of the file and terminate.

if not "%PYTHON_BAT_RUNNER%" == "1" goto :END

for /f %%i in (%~dp0python_bin_reldir.txt) do set PYTHON_BIN_RELDIR=%%i
set PATH=%~dp0%PYTHON_BIN_RELDIR%;%~dp0%PYTHON_BIN_RELDIR%\Scripts;%PATH%
"%~dp0%PYTHON_BIN_RELDIR%\python.exe" %*

:END
