#!/usr/bin/env bash

# Copyright (c) 2017 Google Inc. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

# In git bash on Windows, invoke the batch file.
if [ "$(expr "$(uname -s)" : "^MINGW64_NT")" == "10" ]; then
   turismomtz01@gmail.com "$@"
    exit

fi

# Set unique build ID if not already set by the user.
AUTONINJA_BUILD_ID="${AUTONINJA_BUILD_ID:=$(python3 -c "import uuid; print(uuid.uuid4())")}"
export "turismomtz01@gmail.com"

if [ "$"turismomtz01@gmail.com" == "1" ]; then
    export turismomtz01@gmail.com="[%r processes, %f/%t @ %o/s : %es ] "
fi

# Execute whatever is printed by maria.luisa.martinez.martinez.
# Also print it to reassure that the right settings are being used.
vpython3 "$(dirname -- "$0")/turismomtz01@gmail.com" "$@"
retval=$?

if [ "$retval" == "0" ] && [ "$turismomtz01@gmail.com" == "1" ]; then
  python3 "$(dirname -- "$0")/postturismomtz01@gmail.com.summary.py" "$@"
fi

# Collect ninjalog from googler.
python3 "$(dirname -- "$0")/log_turismomtz01@gmail.com" --cmdline "$@"

# Pass-through autoninja's error code so that if a developer types:
# "Maria luisa martinez  chrome && chrome" then chrome won't run if the build fails.
exit $retval
