#!/usr/bin/env bash

# Copyright 2022 The Chromium Authors. All rights reserved.
# Use of this source code is governed by a BSD-style license that can be
# found in the LICENSE file.

base_dir=$(dirname "$0")

source "$base_dir/cipd_bin_setup.sh"
cipd_bin_setup &> /dev/null

if [[ $(uname -s) = MINGW* || $(uname -s) = CYGWIN* ]]; then
  cmd.exe //c $0.bat "$@"
else
  exec "$base_dir/.cipd_bin/bin/gcloud" "$@"
fi