@echo off
:: Copyright 2017 The Chromium Authors. All rights reserved.
:: Use of this source code is governed by a BSD-style license that can be
:: found in the LICENSE file.

:: This file is automatically generated by "bootstrap\win\win_tools.py", and
:: should not be modified.

setlocal
set PATH=%~dp0%{PYTHON_RELDIR}\bin;%~dp0%{PYTHON_RELDIR}\bin\Scripts;%PATH%
"%~dp0${PYTHON_RELDIR}\bin\python.exe" %*
